remote_theme: "mmistakes/minimal-mistakes@4.24.0"

source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins

plugins:
 - jekyll-gist
 - jekyll-include-cache